package JakartaPM::Model::SiteDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'JakartaPM::Schema::SiteDB',
    
    connect_info => {
        dsn => 'dbi:mysql:jakartapm',
        user => 'root',
        password => '',
    }
);

=head1 NAME

JakartaPM::Model::SiteDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<JakartaPM>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<JakartaPM::Schema::SiteDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Derek J. Curtis <djcurtis@summersetsoftware.com>
Summerset Software, LLC
http://www.summersetsoftware.com

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
